My_list=[1,2,3,4,5,6,7,8,9]
print(My_list)
My_list.append(100)
print(My_list)
My_list[1]=200
print(My_list)
My_list.remove(1)
print(My_list)
My_list[-1]
print(My_list[-1])
print(My_list[::-1])
print(len(My_list))
print(max(My_list))
print(sum(My_list))
print(min(My_list))
print(My_list)
My_list.insert(1,100)
print(My_list)